spring:
  application:
    name: living-alone

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDBDialect

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/OnsiL
    username: root
    password: 1234

server:
  address: 127.0.0.1
  port: 8080